# Generated by Django 3.0.7 on 2020-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='musicfile',
            field=models.FileField(upload_to='portfolio/music/'),
        ),
    ]
