# Generated by Django 3.0.7 on 2020-08-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200810_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='image',
            new_name='album_image',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='album',
            new_name='album_name',
        ),
    ]
